# Generated by Django 2.2 on 2019-04-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outcome',
            old_name='outcome',
            new_name='outcome_type',
        ),
    ]
