# Generated by Django 2.2 on 2019-04-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='last_update',
            new_name='last_update_utc',
        ),
    ]
