# Generated by Django 2.2 on 2019-04-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20190427_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdaymetadata',
            old_name='current_matchday',
            new_name='matchday',
        ),
    ]
