# Generated by Django 2.2 on 2019-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20190426_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDayMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_matchday', models.IntegerField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.IntegerField(null=True),
        ),
    ]
