# Generated by Django 2.2 on 2019-04-26 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('matches', '0002_auto_20190426_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=4)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.Team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='outcome',
            constraint=models.CheckConstraint(check=models.Q(outcome__in=['win', 'loss', 'draw']), name='chk_outcome'),
        ),
    ]
